language: python
python:
  - "2.7"
  #- "3.5"

## system package requirements
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-tk
    - pip install pytest pytest-cov

## command to install dependencies
install: 
    #- pip install -r requirements.txt
    - python setup.py build
    - python setup.py install

## command to run tests
script: 
    - py.test -v --color=yes --exitfirst --showlocals --durations=5

